module.exports = {
    label: `[aria-label="Lead"] .MuiButtonBase-root`,
    typeBtn: 'button[type="button"]',
    inputMob: "input[type='phn']",
    selectStage: ':nth-child(2) > .field > .MuiAutocomplete-root > .MuiFormControl-root > .MuiInputBase-root',
    chooseOptions:'[data-testid="virtuallist-collapse-5aziwjkm5"]',
    saveBtn: '.MuiDialogActions-root > :nth-child(3) > .MuiButtonBase-root',
    inputPipeNeme: 'input[placeholder="Pipeline name"]',
    inputLabel: 'input[placeholder="Label"]',
    propsType: `> .css-8atqhb > .field > .MuiInputBase-root > .MuiInputBase-input`,
    contentSel: '> .css-8atqhb > .field > .MuiFormLabel-root',
    contentGrp: '> .css-8atqhb > .MuiFormLabel-root',
    chooseExportDate: '> .MuiFormControl-root > .MuiInputBase-root > .MuiInputAdornment-root > .MuiButtonBase-root',
    confermationText: `The exported file will be emailed to ${Cypress.env("email")} and posted in your Notification Center.`,
    wrapperInner: '> .MuiCollapse-root > .MuiCollapse-wrapper > .MuiCollapse-wrapperInner >',
    controlLabel: '> .MuiListItem-root > .MuiFormControlLabel-root',
    btnBase: '> .MuiBox-root > .MuiButtonBase-root',
    atqhbBtn: '> .css-8atqhb > .field > button[type=button]',
    filerCaption: '.MuiDrawer-paperAnchorRight .MuiCollapse-wrapperInner .MuiBox-root .MuiTypography-caption',
    searchInfilter: '.MuiDrawer-paperAnchorRight .MuiInputBase-adornedEnd input[placeholder="Search..."]',
    deleteDialogContent: '[role="dialog"] > .MuiDialogContent-root > .MuiCollapse-root > .MuiCollapse-wrapper > .MuiCollapse-wrapperInner .MuiTypography-root',
    arealabelGrid: '#bu-layout [aria-label="Grid view"]',
    selectCheckbox: '.MuiTableHead-root .MuiTableCell-paddingCheckbox input',
    bulkAssignCaption: '[role="dialog"] > .MuiDialogContent-root > .MuiCollapse-root > .MuiCollapse-wrapper  .MuiTypography-caption',
    popperUl: '.MuiPopper-root ul > div >',
    dialogTitle: '[id="customized-dialog-title"] p',
    dialogDesc: '[data-testid="buconfirmation-box-e41vevfuv"] div',
    selectAssociableRecord: '#simple-popper [aria-label="grid"] .ReactVirtualized__Grid__innerScrollContainer >',
    tabpanelBtn: '[role="tabpanel"] .MuiButtonBase-root',
    simpleTab: '[aria-label="Simple Tab"] button',
    formLabel: '.MuiFormLabel-root',
    thead: 'table > thead >',
    tbody: 'table > tbody >',
    countOnGrid: '.MuiTablePagination-displayedRows',
    inputField: `input[name="Select Field Type"]`,
    tooltipHolder: '[role="tooltip"] input[placeholder="Search..."]',
    inputAsset: `input[name="Asset"]`,
    inputTsset: 'input[name="Target Asset"]',
    chkbxOnfieldConfig: '.MuiBox-root > .MuiListItem-root input'
   
}

